Application/EShop.Web/Controllers/CategoryController.cs
using EShop.Core.Domain;
using EShop.Core.Entities;
using EShop.Dtos.Order.Dtos;
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EShop.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [HttpGet]
        public async Task<ActionResult> AddEdit(long? categoryId = null)
        {
            var category = categoryId is null ? null : await _categoryService.GetCategoryAsync(categoryId.Value);
            return View(category);
        }

        [HttpPost]
        public async Task<ActionResult> AddEdit(CategoryDto category)
        {
            if (await _categoryService.AddEditCategoryAsync(category)) {
                return RedirectToAction("CategoryList");
            }

            return View(category);
        }

        public async Task<ActionResult> CategoryList()
        {
            var categories = await _categoryService.GetAllCategoriesAsync();

            return View(categories);
        }

        [HttpPost]
        public async Task<ActionResult> Remove(long categoryId)
        {
            try
            {
                await _categoryService.RemoveCategoryAsync(categoryId);
            } finally {

            }
            return RedirectToAction("CategoryList");
        }
    }
}

Application/EShop.Web/Views/Category/AddEdit.cshtml
@using EShop.Web.Helpers
@model EShop.Dtos.Order.Dtos.CategoryDto

@using (Html.BeginForm("AddEdit", "Category", FormMethod.Post)) {
    if (Model?.Id > 0) {
        <input type="hidden" name="Id" value="@Model.Id"/>
    }

    <div class="row">
        <div class="col-sm-12">
            <label class="form-label">Name</label>
            <input class="form-control" name="Name" value="@(Model != null ? Model.Name : string.Empty)" required/>
        </div>
    </div>
    if(Model == null || Model.IsHidden) {
        <div class="row">
            <div class="col-sm-12">
                <input class="form-check-input" type="checkbox" name="HiddenText" id="flexCheckDefault" @(Model != null && Model.IsHidden ? "checked" : string.Empty)>
                <label class="form-check-label" for="flexCheckDefault">
                    Is Hidden
                </label>
            </div>
        </div>
    }
    <div class="row">
        <div class="col-sm-12">
            @Html.DropDownList("OwnerCategoryId", DropDownListHelper.GetCategories(Model?.OwnerCategoryId), new { @class = "form-select", @value = Model?.OwnerCategoryId })
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <button class="btn btn-primary">Save</button>
        </div>
    </div>
}

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<p>
    @Html.ActionLink("Back to category list", "CategoryList", "Category")
</p>

Application/EShop.Web/Views/Category/CategoryList.cshtml
@using EShop.Web.Helpers
@using System.Activities.Statements
@model System.Collections.Generic.IReadOnlyCollection<EShop.Dtos.Order.Dtos.CategoryDto>

@if (SessionHelper.LoggedUser?.IsAdmin == true) {
    <p>
        @Html.ActionLink("Create New Category", "AddEdit", "Category", new { @class = "btn btn-primary" })
    </p>
}
<table class="table">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Depends on</th>
        <th scope="col">Direct product count</th>
        <th scope="col">Direct category dependencies</th>
        @if (SessionHelper.LoggedUser?.IsAdmin == true) {
            <th scope="col">Is hidden</th>
            <th scope="col">Edit</th>
            <th scope="col">Remove</th>
        }
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <th><a class="btn btn-primary" href="/Product/ProductListByCategory?categoryId=@item.Id">@item.Name</a></th>
            <td>@item.OwnerCategoryName</td>
            <td>@item.ProductCount</td>
            <td>@item.CategoryCount</td>
            @if (SessionHelper.LoggedUser?.IsAdmin == true)
            {
                <td>@item.IsHidden.ToString()</td>
                if (item.ProductCount == 0 && item.CategoryCount == 0)
                {
                    <td>
                        <a class="btn btn-primary" href="/Category/AddEdit?categoryId=@item.Id">Edit</a>
                    </td>
                    <td>
                        <form action="/Category/Remove" method="post">
                            <input type="hidden" name="categoryId" value="@item.Id" />
                            <button class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                }
                else
                {
                    <td>
                        @Html.ActionLink("Edit", "AddEdit", "Category", new { categoryId = item.Id }, new { @class = "btn btn-primary" })
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Remove", "Category", new { categoryId = item.Id }, new { @class = "btn btn-danger disabled" })
                    </td>
                }
            }
        </tr>
    }
    </tbody>
</table>