Application/EShop.Web/Controllers/BasketController.cs
using EShop.Core.Domain;
using EShop.Web.Helpers;
using EShop.Web.Models;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EShop.Web.Controllers
{
    [Authorize]
    [EnforceUser]
    public class BasketController : Controller
    {
        private readonly IBasketService _basketService;
        private readonly IOrderService _orderService;

        public BasketController(IBasketService basketService, IOrderService orderService)
        {
            _basketService = basketService;
            _orderService = orderService;
        }

        public async Task<ActionResult> Index()
        {
            var items = await _basketService.GetBasketItemsAsync(SessionHelper.LoggedUser.Id);

            return View(items);
        }

        [HttpPost]
        public async Task<ActionResult> AddOneMore(long productId)
        {
            await _basketService.AddProductToBasketAsync(SessionHelper.LoggedUser.Id, productId, 1);

            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public async Task<ActionResult> RemoveOne(long productId)
        {
            await _basketService.RemoveItemFromBasketAsync(SessionHelper.LoggedUser.Id, productId, true);

            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public async Task<ActionResult> RemoveAll(long productId)
        {
            await _basketService.RemoveItemFromBasketAsync(SessionHelper.LoggedUser.Id, productId, false);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult CreateOrder()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateOrder(CreateOrderModel model)
        {
            var coreModel = new Dtos.Order.Models.CreateOrderModel() {
                AddressId = model.AddressId,
                PaymentType = model.PaymentType,
                ShippingMethodId = model.ShippingMethodId,
                UserId = SessionHelper.LoggedUser.Id
            };

            var result = await _orderService.CreateOrderAsync(coreModel);

            if (result.HasValue) {
                return RedirectToAction("ViewOrder", "Order", new { orderId = result.Value });
            }

            return View("Index");
        }
    }
}

Application/EShop.Web/Views/Basket/CreateOrder.cshtml
@using EShop.Core.Common.Enums
@using EShop.Web.Helpers

@using (Html.BeginForm("CreateOrder", "Basket", FormMethod.Post)) {
    <div class="row mb-1">
        <div class="col-12">
            <label class="label">Address</label>
            @Html.DropDownList("AddressId", DropDownListHelper.GetAddresses(SessionHelper.LoggedUser.Id), new { @class = "form-select", })
        </div>
    </div>
    <div class="row mb-1">
        <div class="col-12">
            <label class="label">Payment method</label>
            <select name="PaymentType" class="form-select">
                <option value="@PaymentType.Online">Online</option>
                <option value="@PaymentType.OnDelivery">On delivery</option>
            </select>
        </div>
    </div>
    <div class="row mb-1">
        <div class="col-12">
            <label class="label">Shipping method</label>
            @Html.DropDownList("ShippingMethodId", DropDownListHelper.GetShippingMethods(), new { @class = "form-select", })
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button class="btn btn-primary">Complete order</button>
        </div>
    </div>
}

Application/EShop.Web/Views/Basket/Index.cshtml
@model System.Collections.Generic.IReadOnlyCollection<EShop.Dtos.Basket.Dtos.BasketProductDto>

<table class="table">
    <thead>
    <tr>
        <th scope="col"></th>
        <th scope="col">Product Name</th>
        <th scope="col">Count</th>
        <th scope="col">Price per piece</th>
        <th scope="col">Add one more</th>
        <th scope="col">Remove one</th>
        <th scope="col">Remove all</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                <img src="/File/DownloadFile?fileId=@item.FileId" style="max-width: 60px;"/>
            </td>
            <td>@item.ProductName</td>
            <td>@item.Count</td>
            <td>@item.PricePerOne</td>
            <td>
                <form action="/Basket/AddOneMore" method="post">
                    <input type="hidden" name="productId" value="@item.ProductId"/>
                    <button class="btn btn-success">Add one more</button>
                </form>
            </td>
            <td>
                <form action="/Basket/RemoveOne" method="post">
                    <input type="hidden" name="productId" value="@item.ProductId"/>
                    <button class="btn btn-secondary">Remove</button>
                </form>
            </td>
            <td>
                <form action="/Basket/RemoveAll" method="post">
                    <input type="hidden" name="productId" value="@item.ProductId"/>
                    <button class="btn btn-danger">Remove all</button>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>

@if (Model.Count > 0) {
    <a href="/Basket/CreateOrder" class="btn btn-primary">Buy</a>
}